### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.lucene.index.Terms.iterator(Lorg/apache/lucene/index/TermsEnum;)Lorg/apache/lucene/index/TermsEnum

### ISSUE THREAD

**Issue by rhclayto** [renekrie/querqy#17]
On Solr 5.2.1 & Querqy 2.7.0 (querqy-solr-2.7.0-jar-with-dependencies.jar), I'm getting the error referenced in the issue title: java.lang.NoSuchMethodError: org.apache.lucene.index.Terms.iterator(Lorg/apache/lucene/index/TermsEnum;)Lorg/apache/lucene/index/TermsEnum

In Readme.md, it lists the versions of Querqy that match versions of Solr as:

Querqy 2.6.x to 2.7.x - Solr 5.1
Querqy 2.8.x - Solr 5.3.x

If I try with 2.8 I get a different error message.

This issue on another project may be relevant: https://github.com/OpenSextant/SolrTextTagger/issues/40

It states there: 'So annoyingly in Solr 5.2, this method referred to in your stack trace was changed without regard to backward-compatibility. . . . It's a trivial change to the iterator() method; simply drop the argument to take no argument.'

**Comment by renekrie** [comment]
Hi rhclayto,

Thank you for reporting this. Would you mind posting the stack trace (for 5.2.)?

Thanks,
René

**Comment by rhclayto** [comment]
Hi René,

Thanks for looking into this. Here is the stack trace:

```
186586 [qtp1705929636-10] ERROR org.apache.solr.servlet.SolrDispatchFilter  [   tellingua_users] ? null:java.lang.RuntimeException: java.lang.NoSuchMethodError: org.apache.lucene.index.Terms.iterator(Lorg/apache/lucene/index/TermsEnum;)Lorg/apache/lucene/index/TermsEnum;
	at org.apache.solr.servlet.HttpSolrCall.sendError(HttpSolrCall.java:593)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:465)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:227)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:196)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.apache.lucene.index.Terms.iterator(Lorg/apache/lucene/index/TermsEnum;)Lorg/apache/lucene/index/TermsEnum;
	at querqy.lucene.rewrite.DocumentFrequencyCorrection.calculateTermContexts(DocumentFrequencyCorrection.java:86)
	at querqy.lucene.rewrite.DocumentFrequencyCorrection.getDocumentFrequencyAndTermContext(DocumentFrequencyCorrection.java:63)
	at querqy.lucene.rewrite.DependentTermQuery.createWeight(DependentTermQuery.java:62)
	at org.apache.lucene.search.DisjunctionMaxQuery$DisjunctionMaxWeight.<init>(DisjunctionMaxQuery.java:127)
	at org.apache.lucene.search.DisjunctionMaxQuery.createWeight(DisjunctionMaxQuery.java:213)
	at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:851)
	at org.apache.lucene.search.BooleanWeight.<init>(BooleanWeight.java:57)
	at org.apache.lucene.search.BooleanQuery.createWeight(BooleanQuery.java:184)
	at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:851)
	at org.apache.lucene.search.BooleanWeight.<init>(BooleanWeight.java:57)
	at org.apache.lucene.search.BooleanQuery.createWeight(BooleanQuery.java:184)
	at org.apache.lucene.search.FilteredQuery.createWeight(FilteredQuery.java:81)
	at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:851)
	at org.apache.lucene.search.IndexSearcher.createNormalizedWeight(IndexSearcher.java:834)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:485)
	at org.apache.solr.search.SolrIndexSearcher.buildAndRunCollectorChain(SolrIndexSearcher.java:202)
	at org.apache.solr.search.SolrIndexSearcher.getDocListNC(SolrIndexSearcher.java:1666)
	at org.apache.solr.search.SolrIndexSearcher.getDocListC(SolrIndexSearcher.java:1485)
	at org.apache.solr.search.SolrIndexSearcher.search(SolrIndexSearcher.java:561)
	at org.apache.solr.handler.component.QueryComponent.process(QueryComponent.java:518)
	at querqy.solr.QuerqyQueryComponent.process(QuerqyQueryComponent.java:55)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:255)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:143)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2064)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:654)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:450)
	... 22 more

186588 [qtp1705929636-10] WARN  org.eclipse.jetty.servlet.ServletHandler  [   tellingua_users] ? Error for /solr/tellingua_users/select
java.lang.NoSuchMethodError: org.apache.lucene.index.Terms.iterator(Lorg/apache/lucene/index/TermsEnum;)Lorg/apache/lucene/index/TermsEnum;
	at querqy.lucene.rewrite.DocumentFrequencyCorrection.calculateTermContexts(DocumentFrequencyCorrection.java:86)
	at querqy.lucene.rewrite.DocumentFrequencyCorrection.getDocumentFrequencyAndTermContext(DocumentFrequencyCorrection.java:63)
	at querqy.lucene.rewrite.DependentTermQuery.createWeight(DependentTermQuery.java:62)
	at org.apache.lucene.search.DisjunctionMaxQuery$DisjunctionMaxWeight.<init>(DisjunctionMaxQuery.java:127)
	at org.apache.lucene.search.DisjunctionMaxQuery.createWeight(DisjunctionMaxQuery.java:213)
	at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:851)
	at org.apache.lucene.search.BooleanWeight.<init>(BooleanWeight.java:57)
	at org.apache.lucene.search.BooleanQuery.createWeight(BooleanQuery.java:184)
	at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:851)
	at org.apache.lucene.search.BooleanWeight.<init>(BooleanWeight.java:57)
	at org.apache.lucene.search.BooleanQuery.createWeight(BooleanQuery.java:184)
	at org.apache.lucene.search.FilteredQuery.createWeight(FilteredQuery.java:81)
	at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:851)
	at org.apache.lucene.search.IndexSearcher.createNormalizedWeight(IndexSearcher.java:834)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:485)
	at org.apache.solr.search.SolrIndexSearcher.buildAndRunCollectorChain(SolrIndexSearcher.java:202)
	at org.apache.solr.search.SolrIndexSearcher.getDocListNC(SolrIndexSearcher.java:1666)
	at org.apache.solr.search.SolrIndexSearcher.getDocListC(SolrIndexSearcher.java:1485)
	at org.apache.solr.search.SolrIndexSearcher.search(SolrIndexSearcher.java:561)
	at org.apache.solr.handler.component.QueryComponent.process(QueryComponent.java:518)
	at querqy.solr.QuerqyQueryComponent.process(QuerqyQueryComponent.java:55)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:255)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:143)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2064)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:654)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:450)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:227)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:196)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
188666 [qtp1705929636-10] INFO  org.apache.solr.servlet.SolrDispatchFilter  [   ] ? [admin] webapp=null path=/admin/info/logging params={wt=json&since=1468661003078&_=1468661214098} status=0 QTime=2 
198732 [qtp1705929636-12] INFO  org.apache.solr.servlet.SolrDispatchFilter  [   ] ? [admin] webapp=null path=/admin/info/logging params={wt=json&since=1468661184420&_=1468661224176} status=0 QTime=1 
208851 [qtp1705929636-15] INFO  org.apache.solr.servlet.SolrDispatchFilter  [   ] ? [admin] webapp=null path=/admin/info/logging params={wt=json&since=1468661184420&_=1468661234236} status=0 QTime=0 
218938 [qtp1705929636-17] INFO  org.apache.solr.servlet.SolrDispatchFilter  [   ] ? [admin] webapp=null path=/admin/info/logging params={wt=json&since=1468661184420&_=1468661244376} status=0 QTime=1 
229187 [qtp1705929636-13] INFO  org.apache.solr.servlet.SolrDispatchFilter  [   ] ? [admin] webapp=null path=/admin/info/logging params={wt=json&since=1468661184420&_=1468661254447} status=0 QTime=1 
239332 [qtp1705929636-11] INFO  org.apache.solr.servlet.SolrDispatchFilter  [   ] ? [admin] webapp=null path=/admin/info/logging params={wt=json&since=1468661184420&_=1468661264704} status=0 QTime=0 
246250 [qtp1705929636-19] ERROR org.apache.solr.core.SolrCore  [   tellingua_users] ? org.apache.solr.common.SolrException: analyzer returned no terms for multiTerm term: *
	at org.apache.solr.schema.TextField.analyzeMultiTerm(TextField.java:152)
	at org.apache.solr.parser.SolrQueryParserBase.analyzeIfMultitermTermText(SolrQueryParserBase.java:723)
	at org.apache.solr.parser.SolrQueryParserBase.getWildcardQuery(SolrQueryParserBase.java:785)
	at org.apache.solr.parser.SolrQueryParserBase.handleBareTokenQuery(SolrQueryParserBase.java:516)
	at org.apache.solr.parser.QueryParser.Term(QueryParser.java:299)
	at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:185)
	at org.apache.solr.parser.QueryParser.Query(QueryParser.java:107)
	at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:96)
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:151)
	at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:50)
	at org.apache.solr.search.QParser.getQuery(QParser.java:141)
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:203)
	at querqy.solr.QuerqyQueryComponent.prepare(QuerqyQueryComponent.java:30)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:229)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:143)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2064)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:654)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:450)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:227)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:196)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by renekrie** [comment]
Thanks for posting the stack trace - I should be able to look into this over the next couple of days.
René

**Comment by renekrie** [comment]
Hi rhclayto,

I've pushed a version for 5.2.1 to https://github.com/renekrie/querqy/tree/solr_5_2_1 (all tests passing). You should be able to simply do a 'mvn package' from the project root and then use the .jar from querqy-solr/target - let me know in case you run into any problem. 

I can see that this is not a proper release but I hope it will work for you. Starting with the version for Solr 5.5 (to be released soon, together with Querqy for Solr 6) there will be a Querqy version for every Solr version.

- René

**Comment by renekrie** [comment]
Closing this issue. Please create a new issue if a release version for Solr 5.2.1 is required.
