### ISSUE TITLE
NPE in TermQueryCacheValue

### ISSUE THREAD

**Issue by renekrie** [renekrie/querqy#19]
If the Lucene analysis chain removes the only token in a query, a NullPointerException is thrown in  TermQueryCacheValue (branch solr5_1)

org.apache.solr.common.SolrException; null:java.lang.NullPointerException
        at querqy.lucene.rewrite.cache.TermQueryCacheValue.<init>(TermQueryCacheValue.java:18)
        at querqy.lucene.rewrite.TermSubQueryBuilder.termToFactory(TermSubQueryBuilder.java:94)
        at querqy.lucene.rewrite.LuceneQueryBuilder.addTerm(LuceneQueryBuilder.java:293)
        at querqy.lucene.rewrite.LuceneQueryBuilder.visit(LuceneQueryBuilder.java:253)
        at querqy.lucene.rewrite.LuceneQueryBuilder.visit(LuceneQueryBuilder.java:25)
        at querqy.model.Term.accept(Term.java:57)
        at querqy.model.AbstractNodeVisitor.visit(AbstractNodeVisitor.java:23)
        at querqy.lucene.rewrite.LuceneQueryBuilder.visit(LuceneQueryBuilder.java:190)
        at querqy.lucene.rewrite.LuceneQueryBuilder.visit(LuceneQueryBuilder.java:25)
        at querqy.model.DisjunctionMaxQuery.accept(DisjunctionMaxQuery.java:25)
        at querqy.model.AbstractNodeVisitor.visit(AbstractNodeVisitor.java:31)
        at querqy.lucene.rewrite.LuceneQueryBuilder.visit(LuceneQueryBuilder.java:119)
        at querqy.lucene.rewrite.LuceneQueryBuilder.visit(LuceneQueryBuilder.java:105)
        at querqy.lucene.rewrite.LuceneQueryBuilder.createQuery(LuceneQueryBuilder.java:99)
        at querqy.solr.QuerqyDismaxQParser.makeMainQuery(QuerqyDismaxQParser.java:664)
        at querqy.solr.QuerqyDismaxQParser.parse(QuerqyDismaxQParser.java:340)
        at org.apache.solr.search.QParser.getQuery(QParser.java:141)
        at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:157)
        at querqy.solr.QuerqyQueryComponent.prepare(QuerqyQueryComponent.java:30)
        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:196)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:143)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:1984)
        at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:829)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:446)
        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:220)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)

**Comment by renekrie** [comment]
Fixed for solr5_1 to solr6_1
