### ISSUE TITLE
querqy-solr-3.0.0-jar-with-dependencies.jar throws java.lang.ClassNotFoundException: org.apache.lucene.analysis.util.ResourceLoaderAware

### ISSUE THREAD

**Issue by susheelks** [renekrie/querqy#21]
Hello Rene,

I tested 3.0.0 and 3.2.0 versions and 3.0.0 with Solr-6.0.0 fails with below stack trace.

Can you please look into as I was planing to put this into out Solr-6 cluster.

Thanks,
Susheel

1729 INFO  (coreLoadExecutor-6-thread-3) [   x:techproducts] o.a.s.c.CachingDirectoryFactory Closing directory: /Users/kumars5/opt/solr-6.0.0/server/solr/techproducts/data/index
1729 ERROR (coreLoadExecutor-6-thread-3) [   x:techproducts] o.a.s.c.CoreContainer Error creating core [techproducts]: org/apache/lucene/analysis/util/ResourceLoaderAware
org.apache.solr.common.SolrException: org/apache/lucene/analysis/util/ResourceLoaderAware
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:771)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:642)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:817)
	at org.apache.solr.core.CoreContainer.access$000(CoreContainer.java:88)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:468)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:459)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.apache.solr.common.util.ExecutorUtil$MDCAwareThreadPoolExecutor.lambda$execute$0(ExecutorUtil.java:229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: org/apache/lucene/analysis/util/ResourceLoaderAware
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:487)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:520)
	at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:467)
	at org.apache.solr.core.SolrCore.createInstance(SolrCore.java:565)
	at org.apache.solr.core.PluginBag.createPlugin(PluginBag.java:121)
	at org.apache.solr.core.PluginBag.init(PluginBag.java:221)
	at org.apache.solr.core.PluginBag.init(PluginBag.java:210)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:718)
	... 10 more
Caused by: java.lang.ClassNotFoundException: org.apache.lucene.analysis.util.ResourceLoaderAware
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 46 more

**Comment by renekrie** [comment]
Hi Susheel,

The Querqy version for Solr 6.0 is 3.0.x. The latest release is version 3.0.3, which can be found at https://bintray.com/renekrie/maven/querqy-for-lucene/3.0.3#files/querqy/querqy-solr/3.0.3. Querqy normally loads into Solr 6.0 without any issue.
 
org.apache.lucene.analysis.util.ResourceLoaderAware does exist in Solr/Lucene 6.0. I assume that you are seeing some ClassLoader issues. Do you have any other .jar files in Solr's lib folder? Maybe more than one Querqy version? 

Feel free to send me a direct message to setup a walkthrough session in case you cannot resolve the issue.

-- René

**Comment by susheelks** [comment]
Hello Rene,

Indeed I was having multiple versions in different cores.  Sorry for
troubling you. I'll call you directly as well.

Thanks,
Susheel
